export default {
  locale: 'en',
  messages: {
    project_name_long: "National Forecast",
    search_placeholder: "The name of the village, the country or region...",
    min_title: "min.",
    max_title: "max.",
    avg_title: "avg.",
    score_title: "score",
    search_title: "Search",
    signin_action: "SignIn",
    signup_action: "SignUp",
    signout_action: "SignOut",
    email_input_placeholder: "Enter email address",
    password_input_placeholder: "Enter password",
    or_text: "or",
    password_repeat_input_placeholder: "Repeat password",
    temperature_chart: "Value",
    period_1: "Today",
    period_3: "3 days",
    period_5: "5 days",
    period_7: "Week",
  },
};
