export default {
  locale: 'en',
  messages: {
    project_name_short: "NF",
    project_name_long: "National Forecast",
    search_placeholder: "The name of the village, the country or region...",
    min_title: "min.",
    max_title: "max.",
    avg_title: "avg.",
    score_title: "score",
    search_title: "Search",
    signin_action: "Sign In",
    signup_action: "Sign Up",
    signout_action: "Sign Out",
    email_input_placeholder: "Enter email address",
    password_input_placeholder: "Enter password",
    or_text: "or",
    password_repeat_input_placeholder: "Repeat password",
    temperature_chart: "Temperature, °C",
    period_1: "today",
    period_3: "3 days",
    period_5: "5 days",
    period_7: "week",
    already_have_account: "Already have an account?",
    user_exists: "Email address already exists!",
    password_not_equal: "Passwords do not match!",
    meter_per_second: "m/s",
    wind_speed_avg: "Average wind speed",
    wind_gust: "Gust to",
    humidity_title: "Humidity",
    invalid_credential: "Invalid credential",
    subject_input_placeholder: "Subject",
    content_input_placeholder: "Text",
    send_contact_action: "Send",
    internal_error: "Internal Server Error",
    spinner: "LOOKING OUTSIDE FOR YOU... ONE SEC",
  },
};
