export default {
  locale: 'uk',
  messages: {
    project_name_short: "NF",
    project_name_long: "National Forecast",
    search_placeholder: "Назва населеного пункту, країни або регіону...",
    min_title: "мін.",
    max_title: "макс.",
    avg_title: "сер.",
    score_title: "рейтинг",
    search_title: "Пошук",
    signin_action: "Увійти",
    signup_action: "Зареєструватись",
    signout_action: "Вийти",
    email_input_placeholder: "Введіть електронну пошту",
    password_input_placeholder: "Введіть пароль",
    or_text: "або",
    password_repeat_input_placeholder: "Повторіть пароль",
    temperature_chart: "Температура, °C",
    period_1: "сьогодні",
    period_3: "3 дні",
    period_5: "5 днів",
    period_7: "тиждень",
    already_have_account: "Вже є аккаунт?",
    user_exists: "Електронна адреса вже існує!",
    password_not_equal: "Паролі не співпадають!",
    meter_per_second: "м/с",
    wind_speed_avg: "Середня швидкість вітру",
    wind_gust: "Пориви до",
    humidity_title: "Вологість",
    invalid_credential: "Недійсні облікові дані",
    subject_input_placeholder: "Тема",
    content_input_placeholder: "Текст",
    send_contact_action: "Надіслати",
    internal_error: "Серверна помилка",
    spinner: "Розраховуємо прогноз для Вас...",
  },
};
