export default {
  locale: 'uk',
  messages: {
    project_name_long: "National Forecast",
    search_placeholder: "Назва населеного пункту, країни або регіону...",
    min_title: "мін.",
    max_title: "макс.",
    avg_title: "сер.",
    score_title: "рейтинг",
    search_title: "Пошук",
    signin_action: "Увійти",
    signup_action: "Зареєструватись",
    signout_action: "Вийти",
    email_input_placeholder: "Введіть електронну пошту",
    password_input_placeholder: "Введіть пароль",
    or_text: "або",
    password_repeat_input_placeholder: "Повторіть пароль",
    temperature_chart: "температура",
    period_1: "сьогодні",
    period_3: "3 дні",
    period_5: "5 днів",
    period_7: "тиждень",
  },
};
